### ISSUE TITLE
barChartView:barViewAtIndex: not called when reloading bar chart animated

### ISSUE THREAD

**Issue by ersjoh** [Jawbone/JBChartView#207] opened 2016-05-30 23:55 UTC
I've implemented `barChartView:barViewAtIndex:` in my datasource because I'd like to return a custom style (color, alpha value) for a bar view depending on some properties in my data model.

I works great, but when my data model updates and I call `reloadDataAnimated:` with animated equal to true it seems that `barChartView:barViewAtIndex:` is never called. In contrast, when animated is set to false it works.

I had a look at the `reloadDataAnimated:` method and wanted to fix it myself with a PR, but the code seems to be quite complex and extensive. Is this a bug or are there other/better ways to customize the style of a bar view and reload it animated afterwards? Thanks!

**Comment by terryworona** [comment] 2016-05-31 02:05
This is indeed a bug. The issue is in updateExistingBarViewsBlock of reloadData. 

We don't refresh the bar (custom or otherwise) if we are reusing the same view. 

Easy catch. Difficult solution. I'll chew on it for a bit. Feel free to experiment yourself.

**Comment by terryworona** [comment] 2016-05-31 02:37
Fixed via commit: c2558f9975abca4bef3bc745bf7548f7401e633f

Version: [v3.0.10](https://github.com/Jawbone/JBChartView/tree/v3.0.10)

**Closed by terryworona** 2016-05-31 02:37 UTC
Labels: bug

**Comment by ersjoh** [comment] 2016-05-31 08:41
Thank you very much @terryworona for the extremely fast fix! I've just tested it with my set up and it works great. :)
